FamilyNet/Models/ViewModels/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace FamilyNet.Models.ViewModels
{
    public class EditViewModel
    {
        public string Id { get; set; }

        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$")]
        public string PhoneNumber { get; set; }

        public string Email { get; set; }
    }
}

FamilyNet/Controllers/VolunteersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FamilyNet.Models;
using Microsoft.AspNetCore.Authorization;
using FamilyNet.Models.ViewModels;
using FamilyNet.Infrastructure;
using Microsoft.Extensions.Localization;
using EntityFramework.Interfaces;
using EntityFramework.Entities;
using EntityFramework.Identity;

namespace FamilyNet.Controllers {
    [Authorize]
    public class VolunteersController : BaseController {
        #region Fields

        private readonly IStringLocalizer<VolunteersController> _localizer;

        #endregion

        public VolunteersController(IUnitOfWorkAsync unitOfWork, IStringLocalizer<VolunteersController> localizer, IStringLocalizer<SharedResource> sharedLocalizer) : base(unitOfWork, sharedLocalizer) {
            _localizer = localizer;
        }

        // GET: Volunteers
        [AllowAnonymous]
        public async Task<IActionResult> Index(PersonSearchModel searchModel) {

            IEnumerable<Volunteer> volunteers = _unitOfWorkAsync.Volunteers.GetAll();

            volunteers = VolunteerFilter.GetFiltered(volunteers, searchModel);
            GetViewData();

            return View(volunteers);
        }

        // GET: Volunteers/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id) 
        {
            if (id == null) {
                return NotFound();
            }

            var volunteer = await _unitOfWorkAsync.Volunteers.GetById((int)id);
            if (volunteer == null) {
                return NotFound();
            }
         
            return View(volunteer);
        }

        // GET: Volunteers/Create
        [Authorize(Roles = "Admin, Volunteer")]
        public IActionResult Create() {
            var access = CheckAccess().Result;
            

            GetViewData();

            List<Orphanage> orphanagesList = new List<Orphanage>();
            orphanagesList = _unitOfWorkAsync.Orphanages.GetAll().ToList();
            ViewBag.ListOfOrphanages = orphanagesList;

            GetViewData();
            return access == null ? access : View();
        }

        // POST: Volunteers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Volunteer")]
        public async Task<IActionResult> Create([Bind("FullName, Address, Birthday, Contacts")] Volunteer volunteer) {


            if (ModelState.IsValid) {
                await _unitOfWorkAsync.Volunteers.Create(volunteer);
                await _unitOfWorkAsync.Volunteers.SaveChangesAsync();

                var user = await GetCurrentUserAsync();
                user.PersonID = volunteer.ID;
                user.PersonType = PersonType.Volunteer;
                await _unitOfWorkAsync.UserManager.UpdateAsync(user);
                GetViewData();

                return RedirectToAction(nameof(Index));
            }
            GetViewData();

            return View(volunteer);
        }

        // GET: Volunteers/Edit/5
        [Authorize(Roles = "Admin, Volunteer")]
        public async Task<IActionResult> Edit(int? id) {
            GetViewData();

            if (id == null) {
                return NotFound();
            }

            var check = CheckAccess((int)id).Result;
            var checkResult = check != null;
            if (checkResult) {
                return check;
            }

            var volunteer = await _unitOfWorkAsync.Volunteers.GetById((int)id);
            if (volunteer == null) {
                return NotFound();
            }

            return View(volunteer);
        }

        // POST: Volunteers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Volunteer")]
        public async Task<IActionResult> Edit(int id, [Bind("ID, FullName, Address, Birthday, Contacts, Rating")] Volunteer volunteer) {
            GetViewData();

            if (id != volunteer.ID) {
                return NotFound();
            }

            var check = CheckAccess((int)id).Result;
            var checkResult = check != null;
            if (checkResult) {
                return check;
            }

            if (ModelState.IsValid) {
                try {
                    var volunteerToEdit = await _unitOfWorkAsync.Volunteers.GetById(id);
                    volunteerToEdit.CopyState(volunteer);
                    _unitOfWorkAsync.Volunteers.Update(volunteerToEdit);
                    _unitOfWorkAsync.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException) {
                    if (!_unitOfWorkAsync.Volunteers.Any(volunteer.ID)) {
                        return NotFound();
                    }
                    else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(volunteer);
        }

        // GET: Volunteers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) {
                return NotFound();
            }

            var volunteer = await _unitOfWorkAsync.Volunteers
                .GetById((int)id);
            if (volunteer == null) {
                return NotFound();
            }

            ViewData["AreYouSure"] = _localizer["AreYouSure"];

            return View(volunteer);
        }

        // POST: Volunteers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var volunteer = await _unitOfWorkAsync.Volunteers.GetById(id);
            await _unitOfWorkAsync.Volunteers.Delete(volunteer.ID);
            _unitOfWorkAsync.SaveChangesAsync();
            GetViewData();

            return RedirectToAction(nameof(Index));
        }

        #region PrivateHelpers
        private void GetViewData() {
            ViewData["CreateVolonteer"] = _localizer["CreateVolonteer"];
            ViewData["OurVolonteers"] = _localizer["OurVolonteers"];
        }

        #endregion
    }
}

FamilyNet/Views/Volunteers/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> SharedLocalizer
@model EntityFramework.Entities.Volunteer

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@SharedLocalizer["Create"] @ViewData["CreateVolonteer"]</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["PersonName"]</label>
                <input asp-for="FullName.Name" class="form-control" />
                <span asp-validation-for="FullName.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["PersonSurname"]</label>
                <input asp-for="FullName.Surname" class="form-control" />
                <span asp-validation-for="FullName.Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["FathersName"]</label>
                <input asp-for="FullName.Patronymic" class="form-control" />
                <span asp-validation-for="FullName.Patronymic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["Country"]</label>
                <input asp-for="Address.Country" class="form-control" />
                <span asp-validation-for="Address.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["City"]</label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["Region"]</label>
                <input asp-for="Address.Region" class="form-control" />
                <span asp-validation-for="Address.Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["Street"]</label>
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["House"]</label>
                <input asp-for="Address.House" class="form-control" />
                <span asp-validation-for="Address.House" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>@SharedLocalizer["Birthday"]</label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index"><i class="fas fa-chevron-circle-left"></i></a>
                <input type="submit" value=@SharedLocalizer["Create"] class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FamilyNet/Views/Volunteers/Delete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> SharedLocalizer
@model EntityFramework.Entities.Volunteer

@{
    ViewData["Title"] = "Delete";
}

<h1>@SharedLocalizer["Delete"]</h1>

<h3>@ViewData["AreYouSure"]?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @SharedLocalizer["PersonName"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName.Name)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["PersonSurname"]
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName.Surname)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["FathersName"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName.Patronymic)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["Country"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Country)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["City"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.City)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["Region"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Region)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["Street"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Street)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["House"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.House)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["Birthday"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["Rating"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <a asp-action="Index"><i class="fas fa-chevron-circle-left"></i></a>
        <input type="submit" value=@SharedLocalizer["Delete"] class="btn btn-danger" />
    </form>
</div>

FamilyNet/Views/Volunteers/Details.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> SharedLocalizer
@model EntityFramework.Entities.Volunteer

@{
    ViewData["Title"] = "Details";
}

    <h1>@SharedLocalizer["Details"]</h1>

<div>
    <h4>@SharedLocalizer["Volunteer"]</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @SharedLocalizer["PersonName"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName.Name)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["PersonSurname"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName.Surname)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["FathersName"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName.Patronymic)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["Country"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Country)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["City"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.City)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["Region"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Region)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["Street"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Street)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["House"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.House)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["Birthday"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer["Rating"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index"><i class="fas fa-chevron-circle-left"></i></a>
    <a asp-action="Edit" asp-route-id="@Model.ID"><i class="fa fa-marker fa-lg"></i></a>
</div>

FamilyNet/Views/Volunteers/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> SharedLocalizer
@model EntityFramework.Entities.Volunteer

@{
    ViewData["Title"] = "Edit";
}

<h1>@SharedLocalizer["Edit"]</h1>

<h4>@SharedLocalizer["Volunteer"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["PersonSurname"]</label>
                <input asp-for="FullName.Surname" class="form-control" />
                <span asp-validation-for="FullName.Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["PersonName"]</label>
                <input asp-for="FullName.Name" class="form-control" />
                <span asp-validation-for="FullName.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["FathersName"]</label>
                <input asp-for="FullName.Patronymic" class="form-control" />
                <span asp-validation-for="FullName.Patronymic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["Country"]</label>
                <input asp-for="Address.Country" class="form-control" />
                <span asp-validation-for="Address.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["City"]</label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["Region"]</label>
                <input asp-for="Address.Region" class="form-control" />
                <span asp-validation-for="Address.Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["Street"]</label>
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["House"]</label>
                <input asp-for="Address.House" class="form-control" />
                <span asp-validation-for="Address.House" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["Birthday"]</label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@SharedLocalizer["Rating"]</label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index"><i class="fas fa-chevron-circle-left"></i></a>
                <input type="submit" class="btn btn-primary" value=@SharedLocalizer["Save"] />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FamilyNet/Views/Volunteers/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> SharedLocalizer
@model IEnumerable<EntityFramework.Entities.Volunteer>

@{
    ViewData["Title"] = "Index";
}

<h1>@ViewData["OurVolonteers"]</h1>

<form asp-action="Filter">
    <table class="table">
        <th>
            <a>@SharedLocalizer["FullName"]:</a>
            @Html.TextBox("FullNameString", "", new { @class = "form-control" })
        </th>
        <th width="15%">
            <a>@SharedLocalizer["Rating"] @SharedLocalizer["From"]:</a>
            @Html.TextBox("RatingNumber", "", new { @class = "form-control", type = "number" })
        </th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th>
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-filter"></i>
            </button>
            @Html.ActionLink("", "Index", "Volunteers", null, new { @class = "fas fa-ban" })
        </th>

    </table>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @SharedLocalizer["FullName"]
            </th>
            <th>
                @SharedLocalizer["Country"]
            </th>
            <th>
                @SharedLocalizer["City"]
            </th>

            <th>
                @SharedLocalizer["Rating"]
            </th>
            <th><a asp-action="Create" class="btn btn-outline-success"><i class="far fa-plus-square"></i>@SharedLocalizer["Add"]</a></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName.Surname)
                    @Html.DisplayFor(modelItem => item.FullName.Name)
                    @Html.DisplayFor(modelItem => item.FullName.Patronymic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address.Country)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID"><i class="fa fa-marker fa-lg"></i></a>
                    <a asp-action="Details" asp-route-id="@item.ID"><i class="fa fa-list fa-lg"></i></a>
                    <a asp-action="Delete" asp-route-id="@item.ID"><i class="fa fa-trash-alt fa-lg"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>