FamilyNet/Controllers/OrphansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FamilyNet.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using FamilyNet.Models.ViewModels;
using FamilyNet.Infrastructure;

using Microsoft.Extensions.Localization;
using EntityFramework.Interfaces;
using EntityFramework.Entities;
using EntityFramework.Identity;

namespace FamilyNet.Controllers
{
    [Authorize]
    public class OrphansController : BaseController
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IStringLocalizer<OrphansController> _localizer;

        public OrphansController(IUnitOfWorkAsync unitOfWork, IHostingEnvironment environment, IStringLocalizer<OrphansController> localizer) : base(unitOfWork)
        {
            _hostingEnvironment = environment;
            _localizer = localizer;
        }

        // GET: Orphans
        [AllowAnonymous]
        public async Task<IActionResult> Index(int id, PersonSearchModel searchModel)
        {
            IEnumerable<Orphan> orphans = _unitOfWorkAsync.Orphans.GetAll();

            orphans = OrphanFilter.GetFiltered(orphans, searchModel);

            if (id == 0)
                return View(orphans);

            if (id > 0)
                orphans = orphans.Where(x => x.Orphanage.ID.Equals(id)).ToList();
            GetViewData();

            return View(orphans);
        }

        // GET: Orphans/Details/5
        //[HttpGet("[controller]/[action]/{id}")]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orphan = await _unitOfWorkAsync.Orphans.GetById((int)id);
            if (orphan == null)
            {
                return NotFound();
            }
            GetViewData();

            return View(orphan);
        }

        // GET: Orphans/Create
        [Authorize(Roles ="Admin, Orphan")]
        public IActionResult Create()
        {
            var access = CheckAccess().Result;
            

            List <Orphanage> orphanagesList = new List<Orphanage>();
            orphanagesList = _unitOfWorkAsync.Orphanages.GetAll().ToList();
            ViewBag.ListOfOrphanages = orphanagesList;
            GetViewData();

            return access == null ? access : View();
        }

        // POST: Orphans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Orphan")]
        public async Task<IActionResult> Create([Bind("FullName,Address,Birthday,Orphanage,Avatar")] Orphan orphan, int id, IFormFile file)
        {
            await ImageHelper.SetAvatar(orphan, file, "wwwroot\\children");

            if (ModelState.IsValid)
            {
                var orphanage = await _unitOfWorkAsync.Orphanages.GetById(id);
                orphan.Orphanage = orphanage;

                await _unitOfWorkAsync.Orphans.Create(orphan);
                await _unitOfWorkAsync.Orphans.SaveChangesAsync();

                var user = await GetCurrentUserAsync();
                user.PersonID = orphan.ID;
                user.PersonType = PersonType.Orphan;
                await _unitOfWorkAsync.UserManager.UpdateAsync(user);
                

               
                return RedirectToAction(nameof(Index));
            }
            GetViewData();

            return View(orphan);
        }

        // GET: Orphans/Edit/5
        [Authorize(Roles = "Admin, Orphan")]
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var check = CheckAccess((int)id).Result;
            var checkResult = check != null;
            if (checkResult)
            {
                return check;
            }

            List<Orphanage> orphanagesList = _unitOfWorkAsync.Orphanages.GetAll().ToList();
            ViewBag.ListOfOrphanages = orphanagesList;

            var orphan = await _unitOfWorkAsync.Orphans.GetById((int)id);

            if (orphan == null)
            {
                return NotFound();
            }
            GetViewData();

            return View(orphan);
        }

        // POST: Orphans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Orphan")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FullName,Birthday,Orphanage,Avatar")] Orphan orphan, int idOrphanage, IFormFile file)
        {
            if (id != orphan.ID)
            {
                return NotFound();
            }

            var check = CheckAccess((int)id).Result;
            var checkResult = check != null;
            if (checkResult)
            {
                return check;
            }

            await ImageHelper.SetAvatar(orphan, file, "wwwroot\\children");


            if (ModelState.IsValid)
            {
                try
                {
                    var orphanage = await _unitOfWorkAsync.Orphanages.GetById(idOrphanage);
                    orphan.Orphanage = orphanage;
                    var orphanToEdit = await _unitOfWorkAsync.Orphans.GetById(orphan.ID);
                    orphanToEdit.CopyState(orphan);
                    _unitOfWorkAsync.Orphans.Update(orphanToEdit);
                    _unitOfWorkAsync.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_unitOfWorkAsync.Orphans.Any(orphan.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            GetViewData();

            return View(orphan);
        }
       
        // GET: Orphans/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orphan = await _unitOfWorkAsync.Orphans.GetById((int)id);
            if (orphan == null)
            {
                return NotFound();
            }
            GetViewData();

            return View(orphan);
        }

        // POST: Orphans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orphan = await _unitOfWorkAsync.Orphans.GetById((int)id);
            if (orphan == null)
            {
                return RedirectToAction(nameof(Index));
            }
            await _unitOfWorkAsync.Orphans.Delete((int)id);
            _unitOfWorkAsync.SaveChangesAsync();
            GetViewData();

            return RedirectToAction(nameof(Index));
        }

        // GET: Orphans/OrphansTable

        [AllowAnonymous]
        public IActionResult OrphansTable(int id, PersonSearchModel searchModel)
        {
            IEnumerable<Orphan> orphans = _unitOfWorkAsync.Orphans.GetAll();

            orphans = OrphanFilter.GetFiltered(orphans, searchModel);

            if (id == 0)
                return View(orphans);

            if (id > 0)
                orphans = orphans.Where(x => x.Orphanage.ID.Equals(id)).ToList();

            GetViewData();

            return View(orphans);
        }

        private void GetViewData()
        {
            ViewData["OrphansList"] = _localizer["OrphansList"];
        }

        private bool OrphanExists(int id)
        {
            return _unitOfWorkAsync.Orphans.GetById(id) != null;
        }


    }
}

FamilyNet/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using FamilyNet.Models;
using FamilyNet.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using EntityFramework.Interfaces;
using EntityFramework.Identity;

namespace FamilyNet.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : BaseController
    {

        public RolesController(IUnitOfWorkAsync unitOfWork) : base(unitOfWork)
        {

        }
        public IActionResult Index() => View(_unitOfWorkAsync.RoleManager.Roles);

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _unitOfWorkAsync.RoleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _unitOfWorkAsync.RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _unitOfWorkAsync.RoleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_unitOfWorkAsync.UserManager.Users);

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            ApplicationUser user = await _unitOfWorkAsync.UserManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _unitOfWorkAsync.UserManager.GetRolesAsync(user);
                var allRoles = _unitOfWorkAsync.RoleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            ApplicationUser user = await _unitOfWorkAsync.UserManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _unitOfWorkAsync.UserManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _unitOfWorkAsync.RoleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _unitOfWorkAsync.UserManager.AddToRolesAsync(user, addedRoles);

                await _unitOfWorkAsync.UserManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }

    }
}

FamilyNet/Views/Shared/BestOfThree.cshtml
@model IEnumerable<EntityFramework.Entities.Orphanage>

<div class="align-content-lg-center" style="padding-top:100px; padding-bottom:100px">
    <div class="card-group">
        @foreach (var bestofthree in Model)
        {
            <div class="card">
                <button type="button" data-toggle="modal" data-target="#@bestofthree.ID">
                    <img src="@Url.Content("~/avatars/"+@bestofthree.Avatar)" width="1200" height="800" class="img-responsive" alt="">
                </button>
                <div class="card-body">
                    <h5 class="card-title">@bestofthree.Name</h5>
                    <p class="card-text">@bestofthree.Rating</p>
                </div>
            </div>
        }

    </div>
</div>

@foreach (var bestofthree in Model)
{
    <div class="modal fade" id="@bestofthree.ID" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="img-thumbnail">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <img src="@Url.Content("~/avatars/"+@bestofthree.Avatar)" width="1200" height="800" class="img-responsive" alt="">
                </div>
                <div class="modal-content">
                    <div class="row">
                        <div class="col-md-6">
                            <h5 class="card-title">Дом: @bestofthree.Name</h5>
                            <p class="card-text">Адрес @bestofthree.Adress.Country @bestofthree.Adress.City @bestofthree.Adress.Region @bestofthree.Adress.Street @bestofthree.Adress.House</p>
                        </div>
                        <div class="col-md-6 text-center">
                            <button type="button" style="margin-top:5%" class="btn btn-primary">Отозваться</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

FamilyNet/Views/Shared/Filter.cshtml
@model FamilyNet.Models.ViewModels.FilterModel
@{
    Layout = null;
}

<form asp-action="Filter">
    <table class="table">
        @foreach (var item in Model.FilterParam)
        {
        <th>
            @Html.Label(item.ColumnName, item.ColumnName + ":")
            <br />
            @Html.TextBoxFor(m => item.FilterValue, item.FilterValue,  new { @class = "form-control" })
            @*<input asp-for="" class="form-control" />*@
        </th>
        }

        @*<th>
                @Html.Label(@Html.DisplayNameFor(model => model.ToString()) + ":")
                @Html.TextBox("FullNameString", "", new { @class = "form-control" })
            </th>
            <th width="11%">
                @Html.Label(@Html.DisplayNameFor(model => model.ToString()) + " от:")
                @Html.TextBox("RatingNumber", ""
<a href="~/Models/ViewModels/RepresentativeViewModel.cs">~/Models/ViewModels/RepresentativeViewModel.cs</a>, new { @class = "form-control", type = "number" })
            </th>*@
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th>
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-filter"></i>
            </button>
            @*TODO: Work with Person (maybe null contr) <а asp-action="Index"></a> *@
            @Html.ActionLink("", "Index", "Representatives", null, new { @class = "fas fa-ban" })
        </th>

    </table>
</form>

FamilyNet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FamilyNet</title>



    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                crossorigin="anonymous"></script>

        <link rel="stylesheet" href="~/css/albery.css">
        <script src="js/albery.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"
                integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"
                crossorigin="anonymous">
        </script>
    </environment>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/orphanForm.css" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />


    @* For OpenStreetMap *@
    <link href="~/res/External/leaflet/leaflet.css" rel="stylesheet" />
    <link href="~/res/External/leaflet/leaflet-search.css" rel="stylesheet" />
    <link href="~/res/css/main.css" rel="stylesheet" />

    <script src="~/res/External/leaflet/leaflet.js"></script>
    @* --------------------------- *@

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 w-100">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FamilyNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Orphanages" asp-action="Index">@SharedLocalizer["Orphanages"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Orphanages" asp-action="SearchByTypeHelp">@SharedLocalizer["SearchHelp"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Orphans" asp-action="Index">@SharedLocalizer["Orphans"]</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Volunteers" asp-action="Index">@SharedLocalizer["Volunteers"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="CharityMakers" asp-action="Index">@SharedLocalizer["CharityMakers"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Representatives" asp-action="Index">@SharedLocalizer["Representatives"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Donations" asp-action="DonationsTable">@SharedLocalizer["Needs"]</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @SharedLocalizer["Account"]
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <p class="nav-link text-danger font-weight-bold">@User.Identity.Name</p>
                                    <p class="nav-link text-danger font-weight-bold">
                                        <form method="post" asp-controller="Account" asp-action="Logout">
                                            <input style="background-color:lightblue" class="nav-link text-danger alert-dark font-weight-bold fa-pull-right" type="submit" value="Logout" />
                                        </form>
                                    </p>
                                    <p class="nav-link text-danger font-weight-bold">
                                        <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Account" asp-action="PersonalRoom">@SharedLocalizer["PersonalAccount"]</a>
                                    </p>
                                    @*<a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Admin" asp-action="Index"> Админ-панель</a>
                    <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Roles" asp-action="Index">Роль-панель</a>*@
                                </div>
                            </li>
                            <li class="nav-item" style="margin-top:1%">

                                @*<p class="nav-link text-danger font-weight-bold">@User.Identity.Name</p>*@

                            </li>
                            <li class="nav-link" style="margin-top:1%">
                                @*<form method="post" asp-controller="Account" asp-action="Logout">
                    <input style="background-color:lightblue" class="nav-link text-danger alert-dark font-weight-bold" type="submit" value="Logout" />
                </form>*@
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Account" asp-action="Login">@SharedLocalizer["SingIn"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Account" asp-action="Register">@SharedLocalizer["Registration"]</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @SharedLocalizer["Admin"]
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Admin" asp-action="Index"> @SharedLocalizer["AdminPanel"]</a>
                                    <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Roles" asp-action="Index">@SharedLocalizer["RolePanel"]</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - FamilyNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)


</body>
</html>