FamilyNet/Models/ViewModels/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace FamilyNet.Models.ViewModels
{
    public class EditViewModel
    {
        public string Id { get; set; }

        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$")]
        public string PhoneNumber { get; set; }

        public string Email { get; set; }
    }
}

FamilyNet/Controllers/CharityMakersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FamilyNet.Models;
using Microsoft.AspNetCore.Authorization;
using FamilyNet.Models.ViewModels;
using FamilyNet.Infrastructure;
using Microsoft.Extensions.Localization;
using EntityFramework.Interfaces;
using EntityFramework.Entities;
using EntityFramework.Identity;

namespace FamilyNet.Controllers
{
    [Authorize]
    public class CharityMakersController : BaseController
    {
        private readonly IStringLocalizer<CharityMakersController> _localizer;
        
        public CharityMakersController(IUnitOfWorkAsync unitOfWork, IStringLocalizer<CharityMakersController> localizer) : base (unitOfWork)
        {
            _localizer = localizer;
        }

        // GET: CharityMakers
        [AllowAnonymous]
        public IActionResult Index(PersonSearchModel searchModel)
        {
            IEnumerable<CharityMaker> charityMakers =  _unitOfWorkAsync.CharityMakers.GetAll();

            charityMakers = CharityMakerFilter.GetFiltered(charityMakers, searchModel);

            return View(charityMakers);
        }

        // GET: CharityMakers/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charityMaker = await _unitOfWorkAsync.CharityMakers.GetById((int)id);

            if (charityMaker == null)
            {
                return NotFound();
            }

            return View(charityMaker);
        }

        // GET: CharityMakers/Create
        [Authorize(Roles = "Admin, CharityMaker")]
        public IActionResult Create()
        {
            var access = CheckAccess().Result;
            return access == null ? access : View();
        }

        // POST: CharityMakers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, CharityMaker")]
        public async Task<IActionResult> Create([Bind("ID,FullName,Address,Birthday,Contacts,Rating")] CharityMaker charityMaker)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWorkAsync.CharityMakers.Create(charityMaker);
                await _unitOfWorkAsync.CharityMakers.SaveChangesAsync();

                var user = await GetCurrentUserAsync();
                user.PersonID = charityMaker.ID;
                user.PersonType = PersonType.CharityMaker;
                await _unitOfWorkAsync.UserManager.UpdateAsync(user);

                return RedirectToAction(nameof(Index));
            }
            return View(charityMaker);
        }

        // GET: CharityMakers/Edit/5
        [Authorize(Roles = "Admin, CharityMaker")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var check = CheckAccess((int)id).Result;
            var checkResult = check != null;
            if(checkResult)
            {
                return check;
            }

            var charityMaker = await _unitOfWorkAsync.CharityMakers.GetById((int)id);

            if (charityMaker == null)
            {
                return NotFound();
            }

            return View(charityMaker);
        }

        // POST: CharityMakers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, CharityMaker")]
        public async Task<IActionResult> Edit(int id,
            [Bind("ID,FullName,Address,Birthday,Contacts,Rating")] CharityMaker charityMaker)
        {
            var check = CheckAccess((int)id).Result;
            var checkResult = check != null;
            if (checkResult)
            {
                return check;
            }

            if (id != charityMaker.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    CharityMaker charityMakerToEdit = await _unitOfWorkAsync.CharityMakers.GetById(id);
                    charityMakerToEdit.CopyState(charityMaker);
                    _unitOfWorkAsync.CharityMakers.Update(charityMakerToEdit);
                    _unitOfWorkAsync.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_unitOfWorkAsync.CharityMakers.Any(charityMaker.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw; // TODO : logging
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(charityMaker);
        }

        // GET: CharityMakers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CharityMaker charityMaker = await _unitOfWorkAsync.CharityMakers
                .GetById((int)id);

            if (charityMaker == null)
            {
                return NotFound();
            }

            return View(charityMaker);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!_unitOfWorkAsync.CharityMakers.Any(id))
            {
                await _unitOfWorkAsync.CharityMakers.Delete(id);
                _unitOfWorkAsync.SaveChangesAsync();
            }          

            return RedirectToAction(nameof(Index));
        }

        // GET: CharityMakers/Table
        [Authorize(Roles = "Admin")]
        public IActionResult Table()
        {
            var list = _unitOfWorkAsync.CharityMakers.GetAll().ToList();
            return View(list);
        }

        private void GetViewData()
        {
            ViewData["Edit"] = _localizer["Edit"];
            ViewData["BackToList"] = _localizer["BackToList"];
        }

        private bool HasCharityMaker(int id)
        {
            return _unitOfWorkAsync.CharityMakers.GetById(id) != null;
        }
    }
}

FamilyNet/Views/CharityMakers/Create.cshtml
@model EntityFramework.Entities.CharityMaker

@{
    ViewData["Title"] = "Створення мецената";
}

	<h1>Створення мецената</h1>

<h4>Меценат</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName.Name" class="control-label"></label>
                <input asp-for="FullName.Name" class="form-control" />
                <span asp-validation-for="FullName.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName.Surname" class="control-label"></label>
                <input asp-for="FullName.Surname" class="form-control" />
                <span asp-validation-for="FullName.Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName.Patronymic" class="control-label"></label>
                <input asp-for="FullName.Patronymic" class="form-control" />
                <span asp-validation-for="FullName.Patronymic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Country" class="control-label"></label>
                <input asp-for="Address.Country" class="form-control" />
                <span asp-validation-for="Address.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Region" class="control-label"></label>
                <input asp-for="Address.Region" class="form-control" />
                <span asp-validation-for="Address.Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Street" class="control-label"></label>
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.House" class="control-label"></label>
                <input asp-for="Address.House" class="form-control" />
                <span asp-validation-for="Address.House" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avatar" class="control-label"></label>
                <input asp-for="Avatar" type="file" name="file" class="form-control" />
                <span asp-validation-for="Avatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутись до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FamilyNet/Views/CharityMakers/Delete.cshtml
@model EntityFramework.Entities.CharityMaker

@{
    ViewData["Title"] = "Видалення";
}

<h1>Видалення</h1>

<h3>Ви впевненi, що бажаєте видалити це?</h3>
<div>
    <h4>Филантроп</h4>
    <hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Birthday)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Birthday)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.FullName.Name)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.FullName.Name)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.FullName.Surname)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.FullName.Surname)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.FullName.Patronymic);
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.FullName.Patronymic)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Address.Country)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Address.Country)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Address.Region)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Address.Region)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Address.City)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Address.City)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Address.Street)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Address.Street)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Address.House)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Address.House)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Rating)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Rating)
		</dd>
	</dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
		<a asp-action="Index">Повернутися до списку</a>
    </form>
</div>

FamilyNet/Views/CharityMakers/Details.cshtml
@model EntityFramework.Entities.CharityMaker

@{
    ViewData["Title"] = "Деталi";
}

<div class="container">
    <div class="row my-2">
        <div class="col-lg-8 order-lg-2">
            <div class="tab-content py-4">
                <div class="tab-pane active" id="profile">
                    <div class="row">
                        <div class="col-md-6">
                            <h6>@Html.DisplayNameFor(model => model.FullName)</h6>
                            <p>
                                @Html.DisplayFor(model => model.FullName.Surname)
                                @Html.DisplayFor(model => model.FullName.Name)
                                @Html.DisplayFor(model => model.FullName.Patronymic)
                            </p>
                            <h6>@Html.DisplayNameFor(model => model.Birthday)</h6>
                            <p>
                                @Html.DisplayFor(model => model.Birthday)
                            </p>

                            <h6>@Html.DisplayNameFor(model => model.Address)</h6>
                            <p>
                                @Html.DisplayFor(model => model.Address.Country)
                                @Html.DisplayFor(model => model.Address.Region)
                                @Html.DisplayFor(model => model.Address.City)
                                @Html.DisplayFor(model => model.Address.Street)
                                @Html.DisplayFor(model => model.Address.House)
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 order-lg-1 text-center">
            @if (Model.Avatar != null && Model.Avatar != "")
            {
                <img class="img-responsive" src="@Url.Content("~/children/" + Model.Avatar)" alt="Card image cap" style="height: 300px; width: 100%; display: block;" alt="avatar">
            }
            else
            {
                <img class="img-responsive" src="@Url.Content("~/images/anonimusjpg.jpg")" alt="Card image cap" style="height: 300px; width: 100%; display: block;" alt="avatar">
            }
            <label class="custom-file">
                <input type="file" id="file" class="custom-file-input">
            </label>
        </div>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.ID" type="submit" class="btn btn-primary"> <i class="fas fa-edit"></i>Редагувати</a> 
    <a asp-action="Index" type="submit" class="btn btn-primary">Повернутися до списку</a>
</div>

FamilyNet/Views/CharityMakers/Edit.cshtml
@model EntityFramework.Entities.CharityMaker

@{
    ViewData["Title"] = "Редагування";
}

	<h1>Редагування</h1>

<h4>Меценат</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FullName.Name" class="control-label"></label>
                <input asp-for="FullName.Name" class="form-control" />
                <span asp-validation-for="FullName.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName.Surname" class="control-label"></label>
                <input asp-for="FullName.Surname" class="form-control" />
                <span asp-validation-for="FullName.Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName.Patronymic" class="control-label"></label>
                <input asp-for="FullName.Patronymic" class="form-control" />
                <span asp-validation-for="FullName.Patronymic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Country" class="control-label"></label>
                <input asp-for="Address.Country" class="form-control" />
                <span asp-validation-for="Address.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Region" class="control-label"></label>
                <input asp-for="Address.Region" class="form-control" />
                <span asp-validation-for="Address.Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Street" class="control-label"></label>
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.House" class="control-label"></label>
                <input asp-for="Address.House" class="form-control" />
                <span asp-validation-for="Address.House" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avatar" class="control-label"></label>
                <input asp-for="Avatar" type="file" name="file" class="form-control" />
                <span asp-validation-for="Avatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутися до списку</a>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FamilyNet/Views/CharityMakers/Index.cshtml
@model IEnumerable<EntityFramework.Entities.CharityMaker>

@{
    ViewData["Title"] = "Меценати";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>
    Перелік меценатів
    @if (User.IsInRole("Admin"))
    {
        <a asp-action="Table" class="btn btn-primary float-right">Таблиця</a>
    }
</h1><hr />

<form asp-action="Filter">
    <table class="table">
        <th>
            @Html.Label(@Html.DisplayNameFor(model => model.FullName) + ":")
            @Html.TextBox("FullNameString", "", new { @class = "form-control" })
        </th>
        <th width="11%">
            @Html.Label(@Html.DisplayNameFor(model => model.Rating) + " от:")
            @Html.TextBox("RatingNumber", "", new { @class = "form-control", type = "number" })
        </th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th>
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-filter"></i>
            </button>
            @Html.ActionLink("", "Index", "CharityMakers", null, new { @class = "fas fa-ban" })
        </th>

    </table>
</form>


<div class="box">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">

                    <div class="card mb-4 box-shadow text-center">
                        <a asp-action="Details" asp-route-id="@item.ID" style="text-decoration:none;">
                            @if (item.Avatar != null && item.Avatar != "")
                            {
                                <img class="img-responsive" src="@Url.Content("~/children/" + @item.Avatar)" alt="Card image cap" width="100%" height="300px">
                            }
                            else
                            {
                                <img class="img-responsive" src="@Url.Content("~/images/anonimusjpg.jpg")" alt="Card image cap" width="100%" height="300px">
                            }
                            <div class="card-body">
                                <h5 class="card-title">
                                    @Html.DisplayFor(modelItem => item.FullName.Name)
                                    @Html.DisplayFor(modelItem => item.FullName.Surname)
                                </h5>
                                <p class="card-text">
                                    @Html.DisplayFor(modelItem => item.Birthday)
                                </p>
                                <p class="card-text">
                                    Рейтинг
                                    @Html.DisplayFor(modelItem => item.Rating)
                                </p>
                            </div>
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

FamilyNet/Views/CharityMakers/Table.cshtml
@model IEnumerable<EntityFramework.Entities.CharityMaker>

@{
    ViewData["Title"] = "Список";
}

<h1>Список всех филантропов</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Создать</a>
</p>

<form asp-action="Filter">
    <table class="table">
        <th>
            @Html.Label(@Html.DisplayNameFor(model => model.FullName) + ":")
            @Html.TextBox("FullNameString", "", new { @class = "form-control" })
        </th>
        <th width="11%">
            @Html.Label(@Html.DisplayNameFor(model => model.Rating) + " от:")
            @Html.TextBox("RatingNumber", "", new { @class = "form-control", type = "number" })
        </th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th>
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-filter"></i>
            </button>
            @Html.ActionLink("", "Index", "CharityMakers", null, new { @class = "fas fa-ban" })
        </th>

    </table>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Birthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName.Patronymic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address.House)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Birthday)
                </td>
                <th>
                    @Html.DisplayFor(modelItem => item.FullName.Name)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.FullName.Surname)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.FullName.Patronymic)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Address.Country)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Address.Region)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Address.City)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Address.Street)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Address.House)
                </th>

                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID" class="btn btn-sm btn-warning">Редагувати</a>
                    <a asp-action="Details" asp-route-id="@item.ID" class="btn btn-sm btn-info">Деталi</a>
                    <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-sm btn-danger">Видалити</a>
                </td>
            </tr>
        }
    </tbody>
</table>