FamilyNet/Models/ViewModels/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace FamilyNet.Models.ViewModels
{
    public class EditViewModel
    {
        public string Id { get; set; }

        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$")]
        public string PhoneNumber { get; set; }

        public string Email { get; set; }
    }
}

FamilyNet/Controllers/OrphanagesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FamilyNet.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using FamilyNet.Models.ViewModels;
using Microsoft.Extensions.Localization;
using System.Globalization;
using FamilyNet.Infrastructure;
using System;
using System.Collections.Generic;
using EntityFramework.Interfaces;
using EntityFramework.Entities;

namespace FamilyNet.Controllers
{
    [Authorize]
    public class OrphanagesController : BaseController
    {
        #region Private fields

        private OrphanageSearchModel _searchModel;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IStringLocalizer<OrphanagesController> _localizer;

        public OrphanagesController(IUnitOfWorkAsync unitOfWork, IHostingEnvironment environment, IStringLocalizer<OrphanagesController> localizer, IStringLocalizer<SharedResource> sharedLocalizer) : base(unitOfWork, sharedLocalizer)
        {
            _hostingEnvironment = environment;
            _localizer = localizer;
        }

        private bool IsContain(Address addr)
        {
            foreach (var word in _searchModel.AddressString.Split())
            {
                if (addr.Street.ToUpper().Contains(word.ToUpper())
                || addr.City.ToUpper().Contains(word.ToUpper())
                || addr.Region.ToUpper().Contains(word.ToUpper())
                || addr.Country.ToUpper().Contains(word.ToUpper()))
                {
                    return true;
                }
            }
            return false;
        }

        #endregion

        #region ActionMethods

        // GET: Orphanages
        [AllowAnonymous]
        public async Task<IActionResult> Index(int id, OrphanageSearchModel searchModel,
            SortStateOrphanages sortOrder = SortStateOrphanages.NameAsc)
        {
            IQueryable<Orphanage> orphanages = _unitOfWorkAsync.Orphanages.GetAll();

            orphanages = GetFiltered(orphanages, searchModel);
            orphanages = GetSorted(orphanages, sortOrder);

            if (id == 0)
                return View(await orphanages.ToListAsync());

            if (id > 0)
                orphanages = orphanages.Where(x => x.ID.Equals(id));

            return View(await orphanages.ToListAsync());
        }

        // GET: Orphanages/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var orphanage = await _unitOfWorkAsync.Orphanages.GetById((int)id);

            if (orphanage == null)
                return NotFound();
            GetViewData();

            return View(orphanage);
        }

        // GET: Orphanages/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create() => View();

        // POST: Orphanages/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Name,Adress,Rating,Avatar")] Orphanage orphanage,
            IFormFile file) //TODO: AlPa -> Research Bind To Annotations
        {
            await ImageHelper.SetAvatar(orphanage, file, "wwwroot\\avatars");

            //part to add location when obj creating
            bool IsLocationNotNull = GetCoordProp(orphanage.Adress, out var Location);
            if (IsLocationNotNull)
            {
                orphanage.Location = new Location()
                {
                    MapCoordX = Location.Item1,
                    MapCoordY = Location.Item2
                };
            }
            else
                orphanage.LocationID = null;

            if (ModelState.IsValid)
            {
                await _unitOfWorkAsync.Orphanages.Create(orphanage);
                await _unitOfWorkAsync.Orphanages.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            GetViewData();

            return View(orphanage);
        }

        // GET: Orphanages/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var orphanage = await _unitOfWorkAsync.Orphanages.GetById((int)id);

            if (orphanage == null)
                return NotFound();
            GetViewData();

            return View(orphanage);
        }

        // POST: Orphanages/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Representative")]
        public async Task<IActionResult> Edit([Bind("ID,Name,Adress,Rating,Avatar")]
            Orphanage orphanage, int id, IFormFile file) //TODO: Check change id position
        {
            if (id != orphanage.ID)
                return NotFound();

            await ImageHelper.SetAvatar(orphanage, file, "wwwroot\\avatars");

            if (ModelState.IsValid)
            {
                try
                {
                    //in ef to change the object you need to track it out of context
                    var orphanageToEdit = await _unitOfWorkAsync.Orphanages.GetById(orphanage.ID);

                    //copying the state with NOT CHANGING REFERENCES
                    orphanageToEdit.CopyState(orphanage);

                    //edit location
                    bool IsLocationNotNull = GetCoordProp(orphanage.Adress, out var Location);
                    if (IsLocationNotNull)
                    {
                        orphanageToEdit.Location = new Location()
                        {
                            MapCoordX = Location.Item1,
                            MapCoordY = Location.Item2
                        };
                    }
                    else
                        orphanageToEdit.LocationID = null;

                    _unitOfWorkAsync.Orphanages.Update(orphanageToEdit);
                    _unitOfWorkAsync.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_unitOfWorkAsync.Orphanages.Any(orphanage.ID))
                        return NotFound();
                    else
                        throw; //TODO: Loging
                }

                return RedirectToAction(nameof(Index));
            }
            GetViewData();

            return View(orphanage);
        }

        // GET: Orphanages/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var orphanage = await _unitOfWorkAsync.Orphanages.GetById((int)id);

            if (orphanage == null)
                return NotFound();
            GetViewData();

            return View(orphanage);
        }

        // POST: Orphanages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orphanage = await _unitOfWorkAsync.Orphanages.GetById(id);
            await _unitOfWorkAsync.Orphanages.Delete(orphanage.ID);
            _unitOfWorkAsync.SaveChangesAsync();
            GetViewData();

            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public IActionResult SearchByTypeHelp()
        {
            GetViewData();
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult SearchResult(string typeHelp)
        {
            ViewData["TypeHelp"] = typeHelp;
            IEnumerable<Orphanage> list = new List<Orphanage>();
            if(typeHelp != null)
            list = _unitOfWorkAsync.Orphanages.Get(
                orp => orp.Donations.Where(
                    donat => donat.DonationItem.TypeBaseItem.Where(
                        donatitem =>  donatitem.Type.Name.ToLower().Contains(typeHelp.ToLower())).
                        Count() > 0 && donat.IsRequest).
                    Count() > 0);
            GetViewData();

            return View("SearchResult", list);
        }

        [AllowAnonymous]
        public IActionResult SearchOrphanageOnMap()
        {
            var orphanages = _unitOfWorkAsync.Orphanages.GetForSearchOrphanageOnMap();
            GetViewData();

            return View(orphanages);
        }


        #endregion

        #region Private Helpers

        private bool Contains(Address addr)
        {
            foreach (var word in _searchModel.AddressString.Split())
            {
                string wordUpper = word.ToUpper();

                if (addr.Street.ToUpper().Contains(wordUpper)
                        || addr.City.ToUpper().Contains(wordUpper)
                        || addr.Region.ToUpper().Contains(wordUpper)
                        || addr.Country.ToUpper().Contains(wordUpper))
                    return true;
            }

            return false;
        }

        private IQueryable<Orphanage> GetSorted(IQueryable<Orphanage> orphanages, SortStateOrphanages sortOrder)
        {
            ViewData["NameSort"] = sortOrder == SortStateOrphanages.NameAsc
                ? SortStateOrphanages.NameDesc : SortStateOrphanages.NameAsc;
            ViewData["AddressSort"] = sortOrder == SortStateOrphanages.AddressAsc
                ? SortStateOrphanages.AddressDesc : SortStateOrphanages.AddressAsc;
            ViewData["RatingSort"] = sortOrder == SortStateOrphanages.RatingAsc
                ? SortStateOrphanages.RatingDesc : SortStateOrphanages.RatingAsc;

            switch (sortOrder)
            {
                case SortStateOrphanages.NameDesc:
                    orphanages = orphanages.OrderByDescending(s => s.Name);

FamilyNet/Controllers/RepresentativesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FamilyNet.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using FamilyNet.Models.ViewModels;
using FamilyNet.Infrastructure;
using EntityFramework.Interfaces;
using EntityFramework.Entities;

namespace FamilyNet.Controllers
{
    [Authorize]
    public class RepresentativesController : BaseController
    {
        #region Ctor

        public RepresentativesController(IUnitOfWorkAsync unitOfWork) : base(unitOfWork)
        {
        }

        #endregion

        #region Methods

        // GET: Representatives
        [AllowAnonymous]
        public async Task<IActionResult> Index(int id,
            PersonSearchModel searchModel)
        {
            IEnumerable<Representative> representatives = _unitOfWorkAsync.Representatives.GetAll();

            representatives = RepresentativeFilter.GetFiltered(representatives, searchModel);

            if (id == 0)
                return View(representatives);

            if (id > 0)
                representatives = representatives.Where(x => x.Orphanage.ID.Equals(id));

            return View(representatives);
        }

        // GET: Representatives/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var representative = await _unitOfWorkAsync.Representatives.GetById((int)id);

            if (representative == null)
                return NotFound();

            return View(representative);
        }

        [Authorize(Roles = "Admin, Representative")]
        // GET: Representatives/Create
        public async Task<IActionResult> Create()
        {
            var access = CheckAccess().Result;
            

            List<Orphanage> orphanages = await _unitOfWorkAsync.Orphanages.GetAll()
                .OrderBy(o => o.Name).ToListAsync();

            ViewBag.Orphanages = new SelectList(orphanages, "ID", "Name");

            return access == null ? access : View();
        }

        

        // POST: Representatives/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Representative")]
        public async Task<IActionResult> Create([Bind("FullName,Birthday,Rating,Avatar,Orphanage")] 
        Representative representative, int id, IFormFile file)
        {
            await ImageHelper.SetAvatar(representative, file, "wwwroot\\representatives");

            if (ModelState.IsValid)
            {
                var orphanage = await _unitOfWorkAsync.Orphanages.GetById(id);
                representative.Orphanage = orphanage;

                await _unitOfWorkAsync.Representatives.Create(representative);
                await _unitOfWorkAsync.Representatives.SaveChangesAsync();

                var user = await GetCurrentUserAsync();
                user.PersonID = representative.ID;
                user.PersonType = EntityFramework.Identity.PersonType.Representative;
                await _unitOfWorkAsync.UserManager.UpdateAsync(user);

                return RedirectToAction(nameof(Index));
            }
            return View(representative);
        }

        // GET: Representatives/Edit/5
        [Authorize(Roles = "Admin, Representative")]
        public async Task<IActionResult> Edit(int? id)
        {

            List<Orphanage> orphanages = _unitOfWorkAsync.Orphanages.GetAll()
                .OrderBy(o => o.Name).ToList();
            ViewBag.Orphanages = new SelectList(orphanages, "ID", "Name");


            if (id == null)
                return NotFound();

            var check = CheckAccess((int)id).Result;
            var checkResult = check != null;
            if (checkResult)
            {
                return check;
            }

           

            var representative = await _unitOfWorkAsync.Representatives.GetById((int)id);

            if (representative == null)
                return NotFound();

            return View(representative);
        }

        // POST: Representatives/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Representative")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FullName,Birthday,Rating,Avatar,Orphanage")]
         Representative representative, int orphanageId, IFormFile file)
        {
            if (id != representative.ID)
                return NotFound();

            var check = CheckAccess((int)id).Result;
            var checkResult = check != null;
            if (checkResult)
            {
                return check;
            }

            await ImageHelper.SetAvatar(representative, file, "wwwroot\\representatives");

            if (ModelState.IsValid)
            {
                try
                {
                    var orphanage = await _unitOfWorkAsync.Orphanages.GetById(orphanageId);
                    representative.Orphanage = orphanage;

                    var representativeToEdit = await _unitOfWorkAsync.Representatives.GetById(representative.ID);
                    representativeToEdit.CopyState(representative);
                    _unitOfWorkAsync.Representatives.Update(representativeToEdit);
                    _unitOfWorkAsync.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_unitOfWorkAsync.Representatives.Any(representative.ID))
                        return NotFound();
                    else
                        throw; //TODO: Loging
                }

                return RedirectToAction(nameof(Index));
            }

            return View(representative);
        }

        // GET: Representatives/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var representative = await _unitOfWorkAsync.Representatives.GetById((int)id);

            if (representative == null)
                return NotFound();

            return View(representative);
        }

        // POST: Representatives/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var representative = await _unitOfWorkAsync.Representatives.GetById((int)id);
            await _unitOfWorkAsync.Representatives.Delete(representative.ID);
            _unitOfWorkAsync.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        #endregion
    }
}

FamilyNet/Views/Representatives/Create.cshtml
@model EntityFramework.Entities.Representative

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />
<div class="container register" style="background: -webkit-linear-gradient(left, #ffffff, #ffffff);">
    <div class="row">
        <div class="col-md-9 register-right">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <h3 class="register-heading">Создать нового представителя</h3>
                        <div class="row register-form">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="FullName.Name" class="control-label"></label>
                                    <input asp-for="FullName.Name" class="form-control" />
                                    <span asp-validation-for="FullName.Name" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="FullName.Surname" class="control-label"></label>
                                    <input asp-for="FullName.Surname" class="form-control" />
                                    <span asp-validation-for="FullName.Surname" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="FullName.Patronymic" class="control-label"></label>
                                    <input asp-for="FullName.Patronymic" class="form-control" />
                                    <span asp-validation-for="FullName.Patronymic" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Birthday" class="control-label"></label>
                                    <input asp-for="Birthday" class="form-control" />
                                    <span asp-validation-for="Birthday" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Rating" class="control-label"></label>
                                    <input asp-for="Rating" type="number" class="form-control" />
                                    <span asp-validation-for="Rating" class="text-danger"></span>
                                </div>
                                @*TODO: Make with identity*@
                                @*<div class="form-group">
                                    <label asp-for="EmailID" class="control-label"></label>
                                    <input asp-for="EmailID" class="form-control" />
                                    <span asp-validation-for="EmailID" class="text-danger"></span>
                                </div>*@
                                <div class="form-group">
                                    <label asp-for="Orphanage" class="control-label"></label>
                                    <select asp-for="Orphanage.ID"
                                            class="form-control"
                                            name="id"
                                            asp-items="@ViewBag.Orphanages as SelectList"></select>
                                    <span asp-validation-for="Orphanage.Name" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Avatar" class="control-label"></label>
                                    <input asp-for="Avatar" type="file" name="file" class="form-control" />
                                    <span asp-validation-for="Avatar" class="text-danger"></span>
                                    <label> Поддержка только *.jpg</label>
                                </div>
                                <div class="col-md-12 text-center">
                                    <input type="submit" class="btn btn-primary" value="Создать" />
                                    <a asp-action="Index" class="btn btn-primary" type="submit">Вернуться обратно</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FamilyNet/Views/Representatives/Delete.cshtml
@model EntityFramework.Entities.Representative

@{
    ViewData["Title"] = "Delete";
}

<h1>Удаление</h1>

<h3>Вы уверены что хотите удалить предстаивтеля?</h3>
<div>
    <h4>Представитель детдома</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FullName.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FullName.Patronymic)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName.Patronymic)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FullName.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName.Surname)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Avatar)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmailID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmailID)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Orphanage.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Orphanage.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Удалить" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-primary">Вернуться обратно</a>
    </form>
</div>

FamilyNet/Views/Representatives/Details.cshtml
@model EntityFramework.Entities.Representative

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row my-2">
        <div class="col-lg-8 order-lg-2">
            <div class="tab-content py-4">
                <div class="tab-pane active" id="profile">
                    <h5 class="mb-3">Представитель детдома</h5>
                    <div class="row">
                        <div class="col-md-6">
                            <h6>@Html.DisplayNameFor(model => model.FullName)</h6>
                            <p>
                                @Html.DisplayFor(model => model.FullName.Surname)
                                @Html.DisplayFor(model => model.FullName.Name)
                                @Html.DisplayFor(model => model.FullName.Patronymic)
                            </p>
                            <h6>@Html.DisplayNameFor(model => model.Birthday)</h6>
                            <p>
                                @Html.DisplayFor(model => model.Birthday)
                            </p>
                            <h6>@Html.DisplayNameFor(model => model.Rating)</h6>
                            <p>
                                @Html.DisplayFor(model => model.Rating)
                            </p>
                            <h6>@Html.DisplayNameFor(model => model.Orphanage)</h6>
                            <p>
                                @Html.DisplayFor(model => model.Orphanage.Name)
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 order-lg-1 text-center">
            <img src="@Url.Content("~/representatives/" + Model.Avatar)" )" style="height: 300px; width: 100%; display: block;" alt="avatar">
            <label class="custom-file">
                <input type="file" id="file" class="custom-file-input">
            </label>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model.ID">Редактировать</a>
    <a asp-action="Index" class="btn btn-primary">Вернуться обратно</a>
</div>

FamilyNet/Views/Representatives/Index.cshtml
@model IEnumerable<EntityFramework.Entities.Representative>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-6">
        <h2>Представители детодомов</h2>
    </div>
    <div class="col-sm-6 text-right">
        @if (User.IsInRole("Admin"))
        {
            <a asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i></a>
        }
    </div>
</div>

@*TODO: Generic partial filter*@
@*@await Html.PartialAsync("Filter", Model.FilterModel)*@@*, FamilyNet.Infrastructure.FilterUtility.FilterParams)*@

@*@{var representativeColumn = Model.Representatives.FirstOrDefault(); }*@

<form asp-action="Filter">
    <table class="table">
        <th>
            @Html.Label(@Html.DisplayNameFor(model => model.FullName) + ":")
            @Html.TextBox("FullNameString", "", new { @class = "form-control" })
        </th>
        <th width="11%">
            @Html.Label(@Html.DisplayNameFor(model => model.Rating) + " от:")
            @Html.TextBox("RatingNumber", "", new { @class = "form-control", type = "number" })
        </th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th>
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-filter"></i>
            </button>
            @Html.ActionLink("", "Index", "Representatives", null, new { @class = "fas fa-ban" })
        </th>

    </table>
</form>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName.Patronymic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Birthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Avatar)
            </th>
            @*<th> TODO: Add email from Identity
                @Html.DisplayNameFor(model => model.Email)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Orphanage)
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @Html.DisplayFor(modelItem => item.FullName.Name)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.FullName.Patronymic)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.FullName.Surname)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Birthday)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Rating)
                </th>
                <td>
                    <img class="img-responsive" src="@Url.Content("~/representatives/" + @item.Avatar)" alt="" width="50" height="50">
                </td>
                <th>
                    <a asp-action="Index" asp-controller="Orphanages" asp-route-id="@item.ID"
                       class="btn btn-sm btn-outline-primary">
                        <i class="fas fa-home"></i>
                        @Html.DisplayFor(modelItem => item.Orphanage.Name)
                    </a>
                </th>
                <td>
                    <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.ID"><i class="fas fa-info-circle"></i></a>
                    @if (User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.ID"><i class="fa fa-marker fa-lg"></i></a>
                        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.ID"><i class="fa fa-trash-alt fa-lg"></i></a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>